version: '3'
services:
  chat_server:
    build: ./server
    container_name: chat_server
  chat_client:
    build: ./client
    container_name: chat_client
    depends_on:
      - chat_server